// livros-servidor/clientes/livros-next/pages/LivroDados.tsx
import { NextPage } from 'next';
import React, { useState, ChangeEvent } from 'react';
import { useRouter } from 'next/router';
import Livro from '../classes/modelo/Livros';
import ControleLivros from '../classes/controle/ControleLivros';
import { Menu } from '../componentes/Menu';
import Head from 'next/head';

const controleLivros = new ControleLivros('mongodb://localhost:27017');

const LivroDados: NextPage = () => {
  const [livro, setLivro] = useState<Livro>(new Livro(0, 0, '', '', [], ''));
  const router = useRouter();

  const incluirLivro = (): void => {
    controleLivros
      .incluir(livro)
      .then(() => {
        router.push('/LivroLista');
      })
      .catch((error) => {
        console.error('Erro ao incluir o livro:', error);
      });
  };

  const handleChange = (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>): void => {
    const { name, value } = event.target;
    setLivro((livro) => ({ ...livro, [name]: value }));
  };

  return (
    <div>
      <Head>
        <title>Loja Next | Dados do Livro</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Menu />
      <main className="container">
        <h1>Dados do Livro</h1>
        <form>
          <div className="mb-3">
            <label htmlFor="titulo" className="form-label">
              Título
            </label>
            <input
              type="text"
              className="form-control"
              id="titulo"
              name="titulo"
              value={livro.titulo}
              onChange={handleChange}
            />
          </div>
          <div className="mb-3">
            <label htmlFor="resumo" className="form-label">
              Resumo
            </label>
            <textarea
              className="form-control"
              id="resumo"
              name="resumo"
              value={livro.resumo}
              onChange={handleChange}
            ></textarea>
          </div>
          <div className="mb-3">
            <label htmlFor="editora" className="form-label">
              Editora
            </label>
            <input
              type="text"
              className="form-control"
              id="editora"
              name="editora"
              value={livro.editora}
              onChange={handleChange}
            />
          </div>
          <div className="mb-3">
            <label htmlFor="autores" className="form-label">
              Autores
            </label>
            <input
              type="text"
              className="form-control"
              id="autores"
              name="autores"
              value={livro.autores.join(', ')}
              onChange={handleChange}
            />
          </div>
          <button type="button" className="btn btn-primary" onClick={incluirLivro}>
            Incluir
          </button>
        </form>
      </main>
    </div>
  );
};

export default LivroDados;

// livros-servidor/clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  livro: Livro = {
    codigo: '',
    codEditora: 0,
    titulo: '',
    resumo: '',
    autores: []
  };

  constructor(
    private router: Router,
    private controleLivrosService: ControleLivrosService
  ) {}

  ngOnInit(): void {}

  incluir(): void {
    this.controleLivrosService.incluir(this.livro).then(() => {
      this.router.navigateByUrl('/lista');
    });
  }
}


<main class="container mt-5">
    <h2>Novo livro</h2>
  
    <form (submit)="incluir()" ngNativeValidate>
      <div class="form-group">
        <label for="titulo">Título</label>
        <input type="text" class="form-control" id="titulo" name="titulo" required [(ngModel)]="livro.titulo">
      </div>
  
      <div class="form-group">
        <label for="resumo">Resumo</label>
        <textarea class="form-control" id="resumo" name="resumo" [(ngModel)]="livro.resumo" required=""></textarea>
      </div>
  
      <div class="form-group">
        <label for="editora">Editora</label>
        <select class="form-control" id="editora" name="editora" [(ngModel)]="livro.codEditora" required>
          <option value="">Selecione uma editora</option>
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>
      </div>
  
      <div class="form-group">
        <label for="autores">Autores</label>
        <textarea class="form-control" id="autores" name="autores" [(ngModel)]="autoresForm" required=""></textarea>
      </div>
  
      <button type="submit" class="btn btn-primary">Incluir</button>
    </form>
  </main>
