// livros-servidor/clientes/livros-react/src/LivroDados.js
import React, { useState } from 'react';
import { navigate } from '@reach/router';
import ControleLivros from './controle/ControleLivros';

const controleLivros = new ControleLivros();

function LivroDados() {
  const [livro, setLivro] = useState({
    codigo: '',
    codEditora: '',
    titulo: '',
    resumo: '',
    autores: [],
  });

  const atualizarCampo = (campo, valor) => {
    setLivro({ ...livro, [campo]: valor });
  };

  const incluir = () => {
    controleLivros.incluir(livro)
      .then(() => {
        navigate('/');
      });
  };

  return (
    <div>
      <h2>Dados do Livro</h2>
      <div>
        <label>
          Código:
          <input
            type="text"
            value={livro.codigo}
            onChange={(e) => atualizarCampo('codigo', e.target.value)}
          />
        </label>
      </div>
      <div>
        <label>
          Código da Editora:
          <input
            type="text"
            value={livro.codEditora}
            onChange={(e) => atualizarCampo('codEditora', e.target.value)}
          />
        </label>
      </div>
      <div>
        <label>
          Título:
          <input
            type="text"
            value={livro.titulo}
            onChange={(e) => atualizarCampo('titulo', e.target.value)}
          />
        </label>
      </div>
      <div>
        <label>
          Resumo:
          <textarea
            value={livro.resumo}
            onChange={(e) => atualizarCampo('resumo', e.target.value)}
          ></textarea>
        </label>
      </div>
      <div>
        <label>
          Autores:
          <input
            type="text"
            value={livro.autores.join(', ')}
            onChange={(e) => atualizarCampo('autores', e.target.value.split(','))}
          />
        </label>
      </div>
      <button onClick={incluir}>Incluir</button>
    </div>
  );
}

export default LivroDados;

// livros-servidor/clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  livro: Livro = {
    codigo: '',
    codEditora: 0,
    titulo: '',
    resumo: '',
    autores: []
  };

  constructor(
    private router: Router,
    private controleLivrosService: ControleLivrosService
  ) {}

  ngOnInit(): void {}

  incluir(): void {
    this.controleLivrosService.incluir(this.livro).then(() => {
      this.router.navigateByUrl('/lista');
    });
  }
}


<main class="container mt-5">
    <h2>Novo livro</h2>
  
    <form (submit)="incluir()" ngNativeValidate>
      <div class="form-group">
        <label for="titulo">Título</label>
        <input type="text" class="form-control" id="titulo" name="titulo" required [(ngModel)]="livro.titulo">
      </div>
  
      <div class="form-group">
        <label for="resumo">Resumo</label>
        <textarea class="form-control" id="resumo" name="resumo" [(ngModel)]="livro.resumo" required=""></textarea>
      </div>
  
      <div class="form-group">
        <label for="editora">Editora</label>
        <select class="form-control" id="editora" name="editora" [(ngModel)]="livro.codEditora" required>
          <option value="">Selecione uma editora</option>
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>
      </div>
  
      <div class="form-group">
        <label for="autores">Autores</label>
        <textarea class="form-control" id="autores" name="autores" [(ngModel)]="autoresForm" required=""></textarea>
      </div>
  
      <button type="submit" class="btn btn-primary">Incluir</button>
    </form>
  </main>
